<script setup lang="ts">
import { ref } from 'vue'
import { useToast } from '@/composables/useToast'
import { 
  BookOpen, 
  Check, 
  Copy, 
  ExternalLink, 
  ArrowRight,
  HelpCircle,
  Info
} from 'lucide-vue-next'

const { showToast } = useToast()
const copiedSnippet = ref<string | null>(null)

async function copyCode(text: string, label: string) {
  try {
    if (navigator.clipboard && navigator.clipboard.writeText) {
      await navigator.clipboard.writeText(text)
    } else {
      const textarea = document.createElement('textarea')
      textarea.value = text
      textarea.style.position = 'fixed'
      textarea.style.opacity = '0'
      document.body.appendChild(textarea)
      textarea.select()
      document.execCommand('copy')
      document.body.removeChild(textarea)
    }
    copiedSnippet.value = label
    showToast({
      title: 'Command Copied!',
      description: `${label} copied to clipboard.`,
      type: 'success'
    })
    setTimeout(() => {
      if (copiedSnippet.value === label) copiedSnippet.value = null
    }, 2000)
  } catch (err) {
    showToast({
      title: 'Copy Failed',
      description: 'Please manually copy the code block.',
      type: 'error'
    })
  }
}

const gitCommands = `# 1. Initialize local Git repository
git init

# 2. Stage all portfolio files
git add .

# 3. Create initial commit
git commit -m "feat: initial portfolio release"

# 4. Set default branch to main
git branch -M main

# 5. Connect to your GitHub repository (replace USERNAME and REPO)
git remote add origin https://github.com/USERNAME/REPO.git

# 6. Push files to GitHub
git push -u origin main`

const workflowYaml = `name: Deploy Static Portfolio to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: \${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Setup GitHub Pages
        uses: actions/configure-pages@v5

      - name: Upload Static Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4`
</script>

<template>
  <div class="max-w-4xl mx-auto px-4 sm:px-6 py-10 space-y-12 animate-fadeIn">
    
    <!-- Hero Header -->
    <div class="space-y-4 border-b border-slate-200 dark:border-slate-800 pb-8">
      <div class="inline-flex items-center gap-1.5 px-3 py-1 rounded-full bg-indigo-50 dark:bg-indigo-950/60 border border-indigo-200 dark:border-indigo-800 text-indigo-700 dark:text-indigo-300 text-xs font-semibold">
        <BookOpen class="w-3.5 h-3.5 text-indigo-500" />
        Interactive Webinar Tutorial
      </div>
      <h1 class="text-3xl sm:text-4xl font-extrabold text-slate-900 dark:text-white tracking-tight">
        From AI Prompt to Live Website
      </h1>
      <p class="text-base text-slate-600 dark:text-slate-400 max-w-2xl leading-relaxed">
        A step-by-step beginner's guide to generating your portfolio files, running them locally in VS Code, and publishing them online using GitHub Actions & GitHub Pages.
      </p>
    </div>

    <!-- Architecture Clarity Notice -->
    <div class="p-5 rounded-2xl bg-indigo-50/70 dark:bg-indigo-950/40 border border-indigo-200 dark:border-indigo-900/60 space-y-2 text-xs text-indigo-950 dark:text-indigo-200">
      <div class="flex items-center gap-2 font-bold text-sm text-indigo-900 dark:text-white">
        <Info class="w-4 h-4 text-indigo-600 dark:text-indigo-400 shrink-0" />
        Understanding the Two Deployments
      </div>
      <ul class="list-disc list-inside space-y-1 text-slate-700 dark:text-slate-300 ml-1">
        <li><strong>Portfolio Launchpad</strong> (this website): A Vue 3 web app deployed on Vercel that helps you structure your prompt.</li>
        <li><strong>Your Portfolio</strong> (the website you are building): A lightweight static website (HTML/CSS/JS) generated by an AI assistant that lives in your own GitHub repository and deploys via GitHub Actions to GitHub Pages.</li>
      </ul>
    </div>

    <!-- Core Concepts Glossary -->
    <section class="space-y-4">
      <h2 class="text-xl font-bold text-slate-900 dark:text-white tracking-tight flex items-center gap-2">
        <HelpCircle class="w-5 h-5 text-indigo-600" />
        Key Terms for Beginners
      </h2>

      <div class="grid grid-cols-1 sm:grid-cols-2 gap-4 text-xs">
        <div class="card-surface p-4 space-y-1">
          <span class="font-bold text-slate-900 dark:text-white block text-sm">Git</span>
          <p class="text-slate-600 dark:text-slate-400">A version control tool on your computer that tracks the history of your code changes.</p>
        </div>
        <div class="card-surface p-4 space-y-1">
          <span class="font-bold text-slate-900 dark:text-white block text-sm">GitHub & Repository</span>
          <p class="text-slate-600 dark:text-slate-400">GitHub is a cloud platform for storing Git repositories (folders containing your code and project files).</p>
        </div>
        <div class="card-surface p-4 space-y-1">
          <span class="font-bold text-slate-900 dark:text-white block text-sm">GitHub Actions</span>
          <p class="text-slate-600 dark:text-slate-400">An automation workflow tool built into GitHub that automatically tests and deploys your code on every push.</p>
        </div>
        <div class="card-surface p-4 space-y-1">
          <span class="font-bold text-slate-900 dark:text-white block text-sm">GitHub Pages</span>
          <p class="text-slate-600 dark:text-slate-400">A free web hosting service provided by GitHub to publish static HTML, CSS, and JS websites directly to the internet.</p>
        </div>
      </div>
    </section>

    <!-- 10-Stage Walkthrough -->
    <div class="space-y-8">
      
      <!-- Stage 1 -->
      <div class="card-surface p-6 space-y-4 border-l-4 border-indigo-600">
        <div class="flex items-center gap-3">
          <span class="w-7 h-7 rounded-xl bg-indigo-600 text-white font-bold text-xs flex items-center justify-center">1</span>
          <h3 class="text-lg font-bold text-slate-900 dark:text-white">Generate Your Code with an AI Assistant</h3>
        </div>
        <p class="text-xs text-slate-600 dark:text-slate-400 leading-relaxed">
          Copy the structured prompt generated by Portfolio Launchpad and paste it into <span class="font-semibold text-slate-800 dark:text-slate-200">ChatGPT, Google Gemini, Claude, or GitHub Copilot</span>. The AI will output the complete source code for <code class="bg-slate-100 dark:bg-slate-800 px-1.5 py-0.5 rounded font-mono">index.html</code>, <code class="bg-slate-100 dark:bg-slate-800 px-1.5 py-0.5 rounded font-mono">styles.css</code>, and <code class="bg-slate-100 dark:bg-slate-800 px-1.5 py-0.5 rounded font-mono">script.js</code>.
        </p>
      </div>

      <!-- Stage 2 -->
      <div class="card-surface p-6 space-y-4 border-l-4 border-indigo-600">
        <div class="flex items-center gap-3">
          <span class="w-7 h-7 rounded-xl bg-indigo-600 text-white font-bold text-xs flex items-center justify-center">2</span>
          <h3 class="text-lg font-bold text-slate-900 dark:text-white">Create Your Project Folder</h3>
        </div>
        <p class="text-xs text-slate-600 dark:text-slate-400 leading-relaxed">
          Create a new folder on your computer named <code class="bg-slate-100 dark:bg-slate-800 px-1.5 py-0.5 rounded font-mono">my-portfolio</code> and save the three generated files inside it:
        </p>
        <div class="bg-slate-950 text-slate-200 p-4 rounded-xl font-mono text-xs leading-relaxed">
          my-portfolio/<br/>
          ├── index.html<br/>
          ├── styles.css<br/>
          └── script.js
        </div>
      </div>

      <!-- Stage 3 & 4 -->
      <div class="card-surface p-6 space-y-4 border-l-4 border-indigo-600">
        <div class="flex items-center gap-3">
          <span class="w-7 h-7 rounded-xl bg-indigo-600 text-white font-bold text-xs flex items-center justify-center">3 & 4</span>
          <h3 class="text-lg font-bold text-slate-900 dark:text-white">Open in VS Code & Preview Locally</h3>
        </div>
        <p class="text-xs text-slate-600 dark:text-slate-400 leading-relaxed">
          1. Open VS Code and select <strong>File &gt; Open Folder...</strong> to open your <code class="bg-slate-100 dark:bg-slate-800 px-1 py-0.5 rounded font-mono">my-portfolio</code> folder.<br/>
          2. Install the <strong>Live Server</strong> extension in VS Code.<br/>
          3. Right-click <code class="bg-slate-100 dark:bg-slate-800 px-1 py-0.5 rounded font-mono">index.html</code> and select <strong>"Open with Live Server"</strong> to test your site in your browser.
        </p>
      </div>

      <!-- Stage 5, 6 & 7: Git commands -->
      <div class="card-surface p-6 space-y-4 border-l-4 border-indigo-600">
        <div class="flex items-center justify-between">
          <div class="flex items-center gap-3">
            <span class="w-7 h-7 rounded-xl bg-indigo-600 text-white font-bold text-xs flex items-center justify-center">5-7</span>
            <h3 class="text-lg font-bold text-slate-900 dark:text-white">Initialize Git & Push to GitHub</h3>
          </div>
          <button 
            @click="copyCode(gitCommands, 'Git Commands')"
            class="btn-secondary text-xs py-1.5 px-3"
          >
            <Check v-if="copiedSnippet === 'Git Commands'" class="w-3.5 h-3.5 text-emerald-500 mr-1" />
            <Copy v-else class="w-3.5 h-3.5 mr-1" />
            {{ copiedSnippet === 'Git Commands' ? 'Copied!' : 'Copy Commands' }}
          </button>
        </div>

        <p class="text-xs text-slate-600 dark:text-slate-400 leading-relaxed">
          Create a new public repository on <a href="https://github.com/new" target="_blank" class="text-indigo-600 font-semibold underline inline-flex items-center gap-0.5">GitHub <ExternalLink class="w-3 h-3" /></a>, then run these commands inside your project directory in VS Code Terminal:
        </p>

        <div class="bg-slate-950 text-slate-100 p-4 rounded-xl font-mono text-xs overflow-x-auto leading-relaxed whitespace-pre">
{{ gitCommands }}
        </div>
      </div>

      <!-- Stage 8: Actions Workflow File -->
      <div class="card-surface p-6 space-y-4 border-l-4 border-indigo-600">
        <div class="flex items-center justify-between">
          <div class="flex items-center gap-3">
            <span class="w-7 h-7 rounded-xl bg-indigo-600 text-white font-bold text-xs flex items-center justify-center">8</span>
            <h3 class="text-lg font-bold text-slate-900 dark:text-white">Add GitHub Actions Workflow</h3>
          </div>
          <button 
            @click="copyCode(workflowYaml, 'GitHub Actions Workflow')"
            class="btn-secondary text-xs py-1.5 px-3"
          >
            <Check v-if="copiedSnippet === 'GitHub Actions Workflow'" class="w-3.5 h-3.5 text-emerald-500 mr-1" />
            <Copy v-else class="w-3.5 h-3.5 mr-1" />
            {{ copiedSnippet === 'GitHub Actions Workflow' ? 'Copied!' : 'Copy YAML' }}
          </button>
        </div>

        <p class="text-xs text-slate-600 dark:text-slate-400 leading-relaxed">
          Inside your <code class="bg-slate-100 dark:bg-slate-800 px-1 py-0.5 rounded font-mono">my-portfolio</code> project, create the folder path <code class="bg-slate-100 dark:bg-slate-800 px-1.5 py-0.5 rounded font-mono text-indigo-600 dark:text-indigo-400">.github/workflows/deploy.yml</code> and paste the following automated deployment workflow:
        </p>

        <div class="bg-slate-950 text-slate-100 p-4 rounded-xl font-mono text-xs overflow-x-auto leading-relaxed whitespace-pre">
{{ workflowYaml }}
        </div>

        <!-- Setting GitHub Pages Source -->
        <div class="p-4 rounded-xl bg-amber-50 dark:bg-amber-950/40 border border-amber-200 dark:border-amber-900/40 space-y-1 text-xs text-amber-900 dark:text-amber-300">
          <span class="font-bold block">Important Step in GitHub Repository Settings:</span>
          <p>
            Go to your repository on <strong>GitHub.com &gt; Settings &gt; Pages</strong>. Under <strong>Build and deployment &gt; Source</strong>, choose <strong>"GitHub Actions"</strong>.
          </p>
        </div>
      </div>

      <!-- Stage 9 & 10 -->
      <div class="card-surface p-6 space-y-4 border-l-4 border-emerald-600">
        <div class="flex items-center gap-3">
          <span class="w-7 h-7 rounded-xl bg-emerald-600 text-white font-bold text-xs flex items-center justify-center">9 & 10</span>
          <h3 class="text-lg font-bold text-slate-900 dark:text-white">Verify Live Website & Auto-Redeployment</h3>
        </div>
        <p class="text-xs text-slate-600 dark:text-slate-400 leading-relaxed">
          1. Go to the <strong>Actions</strong> tab in your repository to watch the deployment pipeline run.<br/>
          2. Your portfolio will be live at: <code class="bg-slate-100 dark:bg-slate-800 px-1.5 py-0.5 rounded font-mono text-indigo-600 dark:text-indigo-400">https://&lt;username&gt;.github.io/&lt;repository&gt;/</code><br/>
          3. To update your website in the future, simply edit your files, commit, and push to <code class="bg-slate-100 dark:bg-slate-800 px-1 py-0.5 rounded font-mono">main</code>. GitHub Actions will automatically rebuild and deploy your changes in seconds!
        </p>
      </div>

    </div>

    <!-- Ready to build prompt banner -->
    <div class="card-surface p-8 text-center space-y-4 bg-gradient-to-tr from-indigo-50 to-white dark:from-slate-900 dark:to-slate-950 border-indigo-200 dark:border-indigo-900/60">
      <h3 class="text-xl font-bold text-slate-900 dark:text-white">
        Ready to Create Your Custom Portfolio Prompt?
      </h3>
      <p class="text-xs text-slate-600 dark:text-slate-400 max-w-md mx-auto">
        Now that you understand the deployment workflow, fill out your profile details to generate your tailored AI prompt.
      </p>
      <div>
        <router-link to="/builder" class="btn-primary text-xs py-2.5 px-6">
          Open Prompt Builder
          <ArrowRight class="w-4 h-4 ml-2" />
        </router-link>
      </div>
    </div>

  </div>
</template>
