<script setup lang="ts">
import { ref } from 'vue'
import { useToast } from '@/composables/useToast'
import { 
  BookOpen, 
  Check, 
  Copy, 
  ExternalLink, 
  ArrowRight,
  HelpCircle,
  Info
} from 'lucide-vue-next'

const { showToast } = useToast()
const copiedSnippet = ref<string | null>(null)

async function copyCode(text: string, label: string) {
  try {
    if (navigator.clipboard && navigator.clipboard.writeText) {
      await navigator.clipboard.writeText(text)
    } else {
      const textarea = document.createElement('textarea')
      textarea.value = text
      textarea.style.position = 'fixed'
      textarea.style.opacity = '0'
      document.body.appendChild(textarea)
      textarea.select()
      document.execCommand('copy')
      document.body.removeChild(textarea)
    }
    copiedSnippet.value = label
    showToast({
      title: 'Command Copied!',
      description: `${label} copied to clipboard.`,
      type: 'success'
    })
    setTimeout(() => {
      if (copiedSnippet.value === label) copiedSnippet.value = null
    }, 2000)
  } catch (err) {
    showToast({
      title: 'Copy Failed',
      description: 'Please manually copy the code block.',
      type: 'error'
    })
  }
}

const gitCommands = `# 1. Initialize local Git repository
git init

# 2. Stage all portfolio files
git add .

# 3. Create initial commit
git commit -m "feat: initial portfolio release"

# 4. Set default branch to main
git branch -M main

# 5. Connect to your GitHub repository (replace USERNAME and REPO)
git remote add origin https://github.com/USERNAME/REPO.git

# 6. Push files to GitHub
git push -u origin main`

const workflowYaml = `name: Deploy Static Portfolio to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: \${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Setup GitHub Pages
        uses: actions/configure-pages@v5

      - name: Upload Static Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4`
</script>

<template>
  <div class="max-w-4xl mx-auto px-4 sm:px-6 py-8 sm:py-10 space-y-10 animate-fadeIn">
    
    <!-- Hero Header -->
    <div class="space-y-3 border-b border-[#E8E8EF] dark:border-[#232738] pb-6">
      <div class="inline-flex items-center gap-1.5 px-3 py-1 rounded-full bg-[#F2EEFF] dark:bg-brand-950/60 border border-[#E8E8EF] dark:border-[#232738] text-[#6D4AFF] dark:text-brand-300 text-xs font-semibold">
        <BookOpen class="w-3.5 h-3.5 text-[#6D4AFF]" />
        Deployment Tutorial
      </div>
      <h1 class="text-3xl sm:text-4xl font-extrabold text-[#181824] dark:text-[#F3F4F8] tracking-tight">
        From AI Prompt to Live Website
      </h1>
      <p class="text-sm text-[#737385] dark:text-[#9496A8] max-w-2xl leading-relaxed">
        A step-by-step beginner's guide to generating your portfolio files, running them locally in VS Code, and publishing online with GitHub Actions.
      </p>
    </div>

    <!-- Architecture Clarity Notice -->
    <div class="p-4 rounded-2xl bg-[#F2EEFF]/60 dark:bg-brand-950/30 border border-[#E8E8EF] dark:border-[#232738] space-y-1.5 text-xs text-[#181824] dark:text-[#F3F4F8]">
      <div class="flex items-center gap-2 font-bold text-[#6D4AFF]">
        <Info class="w-4 h-4 shrink-0" />
        Understanding the Two Deployments
      </div>
      <ul class="list-disc list-inside space-y-1 text-[#737385] dark:text-[#9496A8] ml-1">
        <li><strong>Portfolio Launchpad</strong> (this website): A Vue 3 SPA deployed on Vercel to help you generate structured prompts.</li>
        <li><strong>Your Portfolio</strong> (the site you are publishing): A lightweight static website (HTML/CSS/JS) generated by AI, living in your GitHub repository, and deployed via GitHub Actions.</li>
      </ul>
    </div>

    <!-- Core Terms -->
    <section class="space-y-3">
      <h2 class="text-lg font-bold text-[#181824] dark:text-[#F3F4F8] tracking-tight flex items-center gap-2">
        <HelpCircle class="w-4 h-4 text-[#6D4AFF]" />
        Essential Concepts
      </h2>

      <div class="grid grid-cols-1 sm:grid-cols-2 gap-3 text-xs">
        <div class="card-surface p-3.5 space-y-0.5">
          <span class="font-bold text-[#181824] dark:text-[#F3F4F8] block">Git</span>
          <p class="text-[#737385] dark:text-[#9496A8]">Version control system on your computer that tracks file changes over time.</p>
        </div>
        <div class="card-surface p-3.5 space-y-0.5">
          <span class="font-bold text-[#181824] dark:text-[#F3F4F8] block">GitHub & Repositories</span>
          <p class="text-[#737385] dark:text-[#9496A8]">Cloud platform for hosting your project folders (repositories) remotely.</p>
        </div>
        <div class="card-surface p-3.5 space-y-0.5">
          <span class="font-bold text-[#181824] dark:text-[#F3F4F8] block">GitHub Actions</span>
          <p class="text-[#737385] dark:text-[#9496A8]">Automation pipeline that builds, tests, and deploys your website on every commit.</p>
        </div>
        <div class="card-surface p-3.5 space-y-0.5">
          <span class="font-bold text-[#181824] dark:text-[#F3F4F8] block">GitHub Pages</span>
          <p class="text-[#737385] dark:text-[#9496A8]">Free static hosting providing a live public URL for your portfolio.</p>
        </div>
      </div>
    </section>

    <!-- 10-Stage Walkthrough -->
    <div class="space-y-6">
      
      <!-- Stage 1 -->
      <div class="card-surface p-5 space-y-2 border-l-4 border-[#6D4AFF]">
        <div class="flex items-center gap-2.5">
          <span class="w-6 h-6 rounded-lg bg-[#6D4AFF] text-white font-bold text-xs flex items-center justify-center">1</span>
          <h3 class="text-sm sm:text-base font-bold text-[#181824] dark:text-[#F3F4F8]">Generate Your Code with an AI Assistant</h3>
        </div>
        <p class="text-xs text-[#737385] dark:text-[#9496A8] leading-relaxed">
          Copy the structured prompt generated by Portfolio Launchpad and paste it into <span class="font-semibold text-[#181824] dark:text-[#F3F4F8]">ChatGPT, Gemini, or Claude</span>. Request complete source code for <code class="bg-[#FAFAFC] dark:bg-[#1A2033] px-1 py-0.5 rounded font-mono text-[#6D4AFF]">index.html</code>, <code class="bg-[#FAFAFC] dark:bg-[#1A2033] px-1 py-0.5 rounded font-mono text-[#6D4AFF]">styles.css</code>, and <code class="bg-[#FAFAFC] dark:bg-[#1A2033] px-1 py-0.5 rounded font-mono text-[#6D4AFF]">script.js</code>.
        </p>
      </div>

      <!-- Stage 2 -->
      <div class="card-surface p-5 space-y-2.5 border-l-4 border-[#6D4AFF]">
        <div class="flex items-center gap-2.5">
          <span class="w-6 h-6 rounded-lg bg-[#6D4AFF] text-white font-bold text-xs flex items-center justify-center">2</span>
          <h3 class="text-sm sm:text-base font-bold text-[#181824] dark:text-[#F3F4F8]">Create Your Project Folder</h3>
        </div>
        <p class="text-xs text-[#737385] dark:text-[#9496A8] leading-relaxed">
          Create a folder named <code class="font-mono text-[#6D4AFF]">my-portfolio</code> on your computer and save the generated files:
        </p>
        <div class="bg-[#0B0D17] text-[#F3F4F8] p-3.5 rounded-xl font-mono text-xs leading-relaxed">
          my-portfolio/<br/>
          ├── index.html<br/>
          ├── styles.css<br/>
          └── script.js
        </div>
      </div>

      <!-- Stage 3 & 4 -->
      <div class="card-surface p-5 space-y-2 border-l-4 border-[#6D4AFF]">
        <div class="flex items-center gap-2.5">
          <span class="w-6 h-6 rounded-lg bg-[#6D4AFF] text-white font-bold text-xs flex items-center justify-center">3 & 4</span>
          <h3 class="text-sm sm:text-base font-bold text-[#181824] dark:text-[#F3F4F8]">Open in VS Code & Preview Locally</h3>
        </div>
        <p class="text-xs text-[#737385] dark:text-[#9496A8] leading-relaxed">
          1. In VS Code, choose <strong>File &gt; Open Folder...</strong> to open <code class="font-mono text-[#6D4AFF]">my-portfolio</code>.<br/>
          2. Right-click <code class="font-mono text-[#6D4AFF]">index.html</code> and click <strong>"Open with Live Server"</strong> to test responsiveness and interactive links in your browser.
        </p>
      </div>

      <!-- Stage 5, 6 & 7 -->
      <div class="card-surface p-5 space-y-3 border-l-4 border-[#6D4AFF]">
        <div class="flex items-center justify-between">
          <div class="flex items-center gap-2.5">
            <span class="w-6 h-6 rounded-lg bg-[#6D4AFF] text-white font-bold text-xs flex items-center justify-center">5-7</span>
            <h3 class="text-sm sm:text-base font-bold text-[#181824] dark:text-[#F3F4F8]">Initialize Git & Push to GitHub</h3>
          </div>
          <button 
            @click="copyCode(gitCommands, 'Git Commands')"
            class="btn-secondary text-xs py-1 px-2.5"
          >
            <Check v-if="copiedSnippet === 'Git Commands'" class="w-3.5 h-3.5 text-emerald-500 mr-1" />
            <Copy v-else class="w-3.5 h-3.5 mr-1" />
            {{ copiedSnippet === 'Git Commands' ? 'Copied!' : 'Copy Commands' }}
          </button>
        </div>

        <p class="text-xs text-[#737385] dark:text-[#9496A8] leading-relaxed">
          Create a public repository on <a href="https://github.com/new" target="_blank" class="text-[#6D4AFF] font-semibold underline inline-flex items-center gap-0.5">GitHub.com <ExternalLink class="w-3 h-3" /></a>, then run in VS Code Terminal:
        </p>

        <div class="bg-[#0B0D17] text-[#F3F4F8] p-3.5 rounded-xl font-mono text-xs overflow-x-auto leading-relaxed whitespace-pre">
{{ gitCommands }}
        </div>
      </div>

      <!-- Stage 8 -->
      <div class="card-surface p-5 space-y-3 border-l-4 border-[#6D4AFF]">
        <div class="flex items-center justify-between">
          <div class="flex items-center gap-2.5">
            <span class="w-6 h-6 rounded-lg bg-[#6D4AFF] text-white font-bold text-xs flex items-center justify-center">8</span>
            <h3 class="text-sm sm:text-base font-bold text-[#181824] dark:text-[#F3F4F8]">Add GitHub Actions Workflow</h3>
          </div>
          <button 
            @click="copyCode(workflowYaml, 'GitHub Actions Workflow')"
            class="btn-secondary text-xs py-1 px-2.5"
          >
            <Check v-if="copiedSnippet === 'GitHub Actions Workflow'" class="w-3.5 h-3.5 text-emerald-500 mr-1" />
            <Copy v-else class="w-3.5 h-3.5 mr-1" />
            {{ copiedSnippet === 'GitHub Actions Workflow' ? 'Copied!' : 'Copy YAML' }}
          </button>
        </div>

        <p class="text-xs text-[#737385] dark:text-[#9496A8] leading-relaxed">
          Inside <code class="font-mono text-[#6D4AFF]">my-portfolio</code>, create the file <code class="font-mono text-[#6D4AFF]">.github/workflows/deploy.yml</code> and paste:
        </p>

        <div class="bg-[#0B0D17] text-[#F3F4F8] p-3.5 rounded-xl font-mono text-xs overflow-x-auto leading-relaxed whitespace-pre">
{{ workflowYaml }}
        </div>

        <div class="p-3 rounded-xl bg-amber-50 dark:bg-amber-950/30 border border-amber-200 dark:border-amber-900/40 text-xs text-amber-900 dark:text-amber-300">
          <strong>GitHub Settings Step:</strong> In your repo on <strong>GitHub.com &gt; Settings &gt; Pages</strong>, set <strong>Build and deployment &gt; Source</strong> to <strong>"GitHub Actions"</strong>.
        </div>
      </div>

      <!-- Stage 9 & 10 -->
      <div class="card-surface p-5 space-y-2 border-l-4 border-emerald-600">
        <div class="flex items-center gap-2.5">
          <span class="w-6 h-6 rounded-lg bg-emerald-600 text-white font-bold text-xs flex items-center justify-center">9 & 10</span>
          <h3 class="text-sm sm:text-base font-bold text-[#181824] dark:text-[#F3F4F8]">Verify Live URL & Automated Updates</h3>
        </div>
        <p class="text-xs text-[#737385] dark:text-[#9496A8] leading-relaxed">
          1. View progress in the <strong>Actions</strong> tab on GitHub.<br/>
          2. Your site is live at: <code class="font-mono text-[#6D4AFF]">https://&lt;username&gt;.github.io/&lt;repo&gt;/</code><br/>
          3. Future commits pushed to <code class="font-mono text-[#6D4AFF]">main</code> will automatically trigger new builds and updates.
        </p>
      </div>

    </div>

    <!-- Ready to build prompt banner -->
    <div class="card-surface p-6 sm:p-8 text-center space-y-3 bg-[#F2EEFF]/40 dark:bg-[#141827]">
      <h3 class="text-lg font-bold text-[#181824] dark:text-[#F3F4F8]">
        Ready to Create Your Custom Portfolio Prompt?
      </h3>
      <p class="text-xs text-[#737385] dark:text-[#9496A8] max-w-sm mx-auto">
        Fill out your profile details to generate your tailored AI coding prompt.
      </p>
      <div>
        <router-link to="/builder" class="btn-primary text-xs py-2 px-5">
          Open Prompt Builder
          <ArrowRight class="w-3.5 h-3.5 ml-1.5" />
        </router-link>
      </div>
    </div>

  </div>
</template>
